- name: Build Android App (APK)
      run: |
        echo "${{ github.run_number }}" > .build_id
        export ANDROID_SDK_ROOT=$ANDROID_HOME
        export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk/26.1.10909125
        
        # Generar archivos de configuración previos
        make src/dmcp/version.h
        make sim/config.qrc sim/state.qrc sim/library.qrc sim/help.qrc sim/help/img.qrc
        cd recorder && make TARGET=opt && cd ..
        
        # Ir a la carpeta del simulador y compilar con las rutas de Qt del servidor (en lugar del Makefile roto)
        cd sim
        $QT_ROOT_DIR/bin/qmake -spec android-clang db48x.pro
        make VARIANT=android
        
        # Preparar las librerías
        mkdir -p ../android/libs/arm64-v8a
        cp libdb48x_arm64-v8a.so ../android/libs/arm64-v8a/
        
        # Generar el APK y firmarlo con nuestra clave temporal (sin --aab)
        $QT_HOST_PATH/bin/androiddeployqt \
          --input android-db48x-deployment-settings.json \
          --output ../android \
          --gradle \
          --sign $HOME/.local/android_release.keystore db48x_alias \
          --storepass 123456
